#pragma once
#include "gpio_pins.h"

#define ON 16
#define OFF 0

#define FREEZE_RED(x) FREEZE_RED_GPIO_Port->BSRR = FREEZE_RED_Pin << (x)
#define FREEZE_GREEN(x) FREEZE_GREEN_GPIO_Port->BSRR = FREEZE_GREEN_Pin << (x)
#define FREEZE_BLUE(x) FREEZE_BLUE_GPIO_Port->BSRR = FREEZE_BLUE_Pin << (x)

#define LEARN_RED(x) LEARN_RED_GPIO_Port->BSRR = LEARN_RED_Pin << (x)
#define LEARN_GREEN(x) LEARN_GREEN_GPIO_Port->BSRR = LEARN_GREEN_Pin << (x)
#define LEARN_BLUE(x) LEARN_BLUE_GPIO_Port->BSRR = LEARN_BLUE_Pin << (x)

#define SET_FREEZE_OFF() FREEZE_RED(OFF), FREEZE_GREEN(OFF), FREEZE_BLUE(OFF)
#define SET_FREEZE_RED() FREEZE_RED(ON), FREEZE_GREEN(OFF), FREEZE_BLUE(OFF)
#define SET_FREEZE_YELLOW() FREEZE_RED(ON), FREEZE_GREEN(ON), FREEZE_BLUE(OFF)
#define SET_FREEZE_GREEN() FREEZE_RED(OFF), FREEZE_GREEN(ON), FREEZE_BLUE(OFF)
#define SET_FREEZE_BLUE() FREEZE_RED(OFF), FREEZE_GREEN(OFF), FREEZE_BLUE(ON)
#define SET_FREEZE_WHITE() FREEZE_RED(ON), FREEZE_GREEN(ON), FREEZE_BLUE(ON)

#define SET_LEARN_OFF() LEARN_RED(OFF), LEARN_GREEN(OFF), LEARN_BLUE(OFF)
#define SET_LEARN_RED() LEARN_RED(ON), LEARN_GREEN(OFF), LEARN_BLUE(OFF)
#define SET_LEARN_YELLOW() LEARN_RED(ON), LEARN_GREEN(ON), LEARN_BLUE(OFF)
#define SET_LEARN_GREEN() LEARN_RED(OFF), LEARN_GREEN(ON), LEARN_BLUE(OFF)
#define SET_LEARN_BLUE() LEARN_RED(OFF), LEARN_GREEN(OFF), LEARN_BLUE(ON)
#define SET_LEARN_WHITE() LEARN_RED(ON), LEARN_GREEN(ON), LEARN_BLUE(ON)

void init_leds(void);
